name: docker-build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-18.04
    name: auto build docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
          repository: yobot/yobot
          dockerfile: scripts/slim.Dockerfile
          tags: latest,slim

      - name: Build image on pypy
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESSTOKEN }}
          repository: yobot/yobot
          dockerfile: scripts/pypy.Dockerfile
          tags: pypy
